### ISSUE TITLE
Fix How Providers are Associated with Users

### ISSUE THREAD

**Issue by benjibrandt** [scalableinternetservices/whispr#25]
Currently, it seems like all users are automatically associated with themselves, and any provider that exists. The process should flow like this:

1. User is presented with a list of all providers. Can select them as he/she pleases.
2. User can edit their selections at any time via their profile.
3. Providers can search for users, and request access.
   a. Users will be able to see incoming requests, and approve/reject them. If approved, they'll be able to be managed via the profile exactly as if the user had sought them out to start.

**Comment by benjibrandt** [comment]
@moojink Did you have a fix for this in the works already, or was it just an issue you were aware of?

**Comment by moojink** [comment]
Tasks 1 and 2 are done in branch `add_providers2`.

**Comment by moojink** [comment]
Task 3 finished. See https://github.com/scalableinternetservices/whispr/pull/36
